spring.application.name=api-crud

# Configurando banco postgres
spring.jpa.database=POSTGRESQL
spring.datasource.plataform=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/api_demo
spring.datasource.username=postgres
spring.datasource.password=12345

# Hibernate
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl=update
spring.jpa.show-sql=true


# Mode de desenvolvimento
spring.profiles.active=dev

logging.level.org.springframework.security=DEBUG
